kivudesign/Wepesi

class/app/Hash.php
Could you use password_hash ( string $password , mixed $algo [, array $options ] ) : string instead of using hash?
=> Update Hashing Algorithm to BCRYPT

README.md
correct some error on the description
and give more detail about the library it self
=> add more description an the library

class/app/BoxMessage.php, class/app/Controller.php, class/app/Validate.php, class/app/View.php, config/global.php, config/init.php, lang/en.php, lang/fr.php
- add check file extension
- make controller flexible with sub folder
- fx validation language
- fix check unique value on the validation key
- fix box message multi language support
=> add library multi language support

class/app/View.php
=> change file link check test

composer.json, config/global.php, config/init.php, index.php, route/index.php, src/core/routing/Router.php, views/index.php
The was a conflix whill try to access src module class
=> [FIX] fixed missed autoload module

composer.json, config/global.php, src/core/Email.php
[FEAT] add email model templating
=> [FEAT] add email model templating

src/core/Input.php
[FEAT] get json data from post/put request Closes #20
=> [FEAT] get json data from post/put request

.idea/php.xml, .idea/wepesi.iml, src/core/Media.php
manage to access undefined key field while try to upload a file. Closes #26
=> fix: manage access undefined key field

src/core/JWT.php
give  the abilty to difine the expired time as datetime Closes #
=> fix: add expired time as datatime

src/Core/View.php
=> [FIX] View: missing file to render

.github/workflows/php.yml
This will be help for CI/CD and will be reconfigure
=> add php.yml

src/Core/Escape.php, src/Core/Orm/DB.php, src/Core/Redirect.php, src/Core/Validation/VDate.php, src/Core/Validation/VFile.php, src/Core/Validation/VNumber.php, src/Core/Validation/VString.php, src/Core/Validation/VTime.php, src/Core/Validation/Validate.php, src/Core/View.php
[[FIX] views: resolve problem with subfolder once] : make assy to support subfolder wile creating a view
[[FIX] validation: remove unused key not apropiated to th context] : cleaning app project
[[FIX] DB : call undifined config class with does not exist.] : until refactor from ps-4 standar some class where not well set
[[UPD] Escape : update Escape module to manage slache and file extension.] 
[[UPD] View :  make view to be more dynamic with paths.]
[[UPD] Response : add more response in case there is a link or there is no file a…]
=> [ENH] make validation better

composer.json, config/globals.php, controller/homeController.php, global/constant.php, global/init.php, route/web.php, src/Core/Escape.php, src/Core/Validation/VDate.php, src/Core/Validation/VFile.php, src/Core/Validation/VNumber.php, src/Core/Validation/VString.php, src/Core/Validation/VTime.php
- [UPD] add more response in case there is a link or there is no file
- [UPD] setup defaut general language for the project
- [UPD] Review and refactoring redirection view
- [UPD] keyword project
- [UPD] Review and refactor validation module
- [UPD] Remove unused module validation
=> [UPD] Review and refactoring app

route/web.php, src/Core/Routing/Route.php, src/Core/Routing/Router.php, src/Core/View.php
it will be now possible to group routing via method group.
=> [ENH] Routing: add support for group routing

src/Core/Validation/VString.php, src/Core/Validation/Validate.php
use of undefined global variable and add error message while can not
=> [FIX] Used of undefined global variable

src/Core/Routing/Route.php, src/Core/Routing/Router.php
=> [UPD] Routing: make possible to run routing via cli

controller/homeController.php, index.php, route/route.php, src/Core/AppConfiguration.php, src/Core/Application.php, src/Core/Controller.php, src/Core/CoreException/RoutingException.php, src/Core/MiddleWare.php, src/Core/Response.php, src/Core/Routing/Route.php, src/Core/Routing/Router.php, src/Core/Routing/Traits/routeBuilder.php, views/home.php
The project routing require a little bit refactoring to manage group middleware and add support to custom trigger 404 path.
closes #75
=> [ENH] routing refactor routing to support group middleware and trigger404

route/api.php, route/route.php, src/Core/Response.php, src/Core/Routing/Router.php
The api rouing will help write effentient api routing.
closes #79
=> [ENH] add api routing support.

index.php, router/api.php, router/route.php, src/Core/AppConfiguration.php, src/Core/Application.php, src/Core/ApplicationBase.php, src/Core/Bundles.php, src/Core/Config.php, src/Core/Escape.php, src/Core/Hash.php, src/Core/I18n.php, src/Core/Input.php, src/Core/JWT.php, src/Core/MetaData.php, src/Core/Redirect.php, src/Core/Response.php, src/Core/Session.php, src/Core/Token.php, src/Core/View.php, views/home.php
[[UPD] review and update documentation]
closes #86
[[UPD] refactor metadata class]
[[UPD] refactor Bundles class
closes #85
[[UPD] refactor project application]
closes #84
=> Version boss

src/Core/Orm/WhereQueryBuilder/WhereConditions.php, src/Core/Validation/Schema/StringSchema.php
There is a problem while writing where conditions, there is another cast that add extra information to the field value that will make the condition to return false or empty for some case.
closes #99
=> [Fix] fix where condition cast field value.

src/Core/Routing/Route.php, src/Core/Routing/Router.php
The groupe routing does not work as expected.
closes #106
=> [FIX] group middleware return empty array

src/Core/Routing/Router.php
Add missing routing methods they are very useful for Api applications.
closes #108
=> [ENH] add support for other routing method

index.php, src/Core/BaseEntityModel/EntityReflexion.php, src/Core/BaseEntityModel/Provider/Contract/EntityInterface.php, src/Core/BaseEntityModel/Provider/Entity.php, src/Core/Orm/DBSelect.php, src/Core/Orm/Relations/BaseRelation.php, src/Core/Orm/Relations/HasOne.php
Alot of improvement.
No you can use as Hasmany and HasOne relation model for the request.
closes #117 
close #116 
close #115
=> [ENH] refactoring orm relation and add one relation

src/Core/Orm/EntityModel/Provider/Entity.php
The count method will help to get the total count of item records on a table.
closes #127 .
=> [ENH] add missing count method for entity model

src/Core/Input.php
While check the request use to call and undefined `_put` method which as been updated to `put`.
closes #132
=> [FIX] Request Input:call to undefined method _input.

middleware/Validation/exampleValidation.php, router/route.php, src/Core/Resolver/OptionsResolver.php, src/Core/Routing/Router.php, src/Core/Validation/MessageErrorBuilder.php, src/Core/Validation/Providers/Contracts/MessageBuilderContracts.php, src/Core/Validation/Validate.php
While doing validation in case there is a key property label defined but cannot be retrieve from both sides, it will be catch with the option resolver and be display as `unknow` but instean of the the oprtion resolve throw as an eception an the server crash.
=> [FIX] Validation :undefined prop key crash the application.

router/api.php, src/Core/Http/Input.php, src/Core/Http/Redirect.php, src/Core/Http/Response.php, src/Core/Routing/Router.php, src/Core/Validation/Validate.php, src/Core/View.php
=> [ENH] Migrate Input, Redirect and response to http namespace.

config/constant.php, config/init.php
The idea is to remove all function or logic from constant file to somewhere else. knowing that we need some information from the function to be used on the constant.
=> [UPD] remove serverdomain provider information from constant to the init file.

src/Core/Orm/DB.php, src/Core/Orm/Traits/QueryExecuter.php
Based on previous update to formatted data, the query method output data that was not easy to work with it required a large process to get formatted data. so the solution is to provided usable data .
=> [FIX] db query method to display usable data .

config/function.php
There was a missing is verry useful. It a short cut,  help apply translation on the application without the need to call the translation module each time we need to translate.
closes #168
=> [ENH] add simplify translation funtion

composer.json, src/Core/View.php
Based on the recent update it was responsible of a regression on Missing class module.
closes #170 
closes #171
=> [ENH] update composer for requirement module

src/Core/Http/Request.php
The http requestion class will be integrated to `Input` class to load data from http request.
=> [ENH] introduce http request module

composer.json, composer.lock
This is new chapter and new approached it will help to benefit all improvement from PHP 8
=> [ENH] Migrate to PHP 8.0

controller/exampleController.php, index.php, router/api.php, router/route.php, routes/api.php, routes/web.php, src/Core/Application.php, src/Core/Bundles.php, src/Core/Routing/Providers/Contracts/RouteContract.php, src/Core/Routing/Providers/Contracts/RouterContract.php, src/Core/Routing/Providers/Contracts/RouterProviders.php, src/Core/Routing/Route.php, src/Core/Routing/RouteFileRegistrar.php, src/Core/Routing/Router.php, src/Core/Routing/Traits/routeBuilder.php, src/Core/Views/Provider/ViewBuilderProvider.php, src/Core/Views/View.php
[[UPD] refactoring to access root directory via getter method]
[[UPD] refactoring to access layout path via getter method]
[[UPD] refactoring to access layout param via getter method] 
[[ENH] refactoring routing system to be more flexibility and manageable …]
[[ENH] refactoring routes path based on new structure]
#183 #182 #177
=> [ENH] Refactoring routing for more flexibility

src/Core/AppConfiguration.php, src/Core/Application.php, src/Core/Orm/DBConfig.php
The database configuration was managed to be setup on the root, now everything has been setup from application features, the only thing is to setup the .env file.
closes #179
=> [ENH] Setup db configuration to setup on application module

src/Core/Database/DBDelete.php, src/Core/Database/DBSelect.php, src/Core/Database/DBUpdate.php, src/Core/Database/Providers/BaseEntity.php, src/Core/Database/Providers/Contracts/WhereConditionContracts.php, src/Core/Database/Traits/DBWhereCondition.php, src/Core/Database/WhereQueryBuilder/WhereBuilder.php, src/Core/Database/WhereQueryBuilder/WhereConditions.php
Make possible to be able to a simple array key to create a where condition while doing a requestion without using the WhereBuilder.
closes #210 
closes #208
=> [REF] revert to support simple array where condition.
