kivudesign/Wepesi

index.php, src/Core/Application.php, src/Core/View.php
It will be easy to point all view file on the view folder directly without thinking where it will be located.
closes #93
=> [ENH] setup application layout to point into views folder.

src/Core/Validation/Schema/StringSchema.php, src/Core/Validation/Validator/StringValidator.php
Unique validation schema function was not available while exist on previous version.
closes #100
=> [Fix] Add missing unique condition that where not accessible

src/Core/Validation/Providers/ValidatorProvider.php, src/Core/Validation/Validator/ArrayValidator.php, src/Core/Validation/Validator/NumberValidator.php, src/Core/Validation/Validator/StringValidator.php
While validate a schema, in case the condition where meet unexpectedly it return error, but when the condition is not met it passed, which was confusing. the problem come from a module that help to validate positive value.
closes #98
=> [Fix] this module make the validation return false result while the condition where exact.

src/Core/Response.php
While pass sting value to the `send` method the response is not read as Json value, which cause some problems to the user interface response.
closes #97
=> [UPD] format any data to json.

src/Core/Bundles.php
missing an `s` on the file location that make the file to not be accessible.
closes #96
=> [FIX] missing valid js file location.

controller/homeController.php, src/Core/BaseEntityModel/Provider/Contract/EntityInterface.php, src/Core/Orm/EntityModel/EntityReflexion.php, src/Core/Orm/EntityModel/Provider/Contract/EntityInterface.php, src/Core/Orm/EntityModel/Provider/Entity.php, src/Core/Orm/Relations/BaseRelation.php, src/Core/Orm/Relations/HasMany.php, src/Core/Orm/Relations/HasOne.php
It required to restructure the entity into the ORM module because it was linked.
closes #120
=> [ENH] refactoring entity structure into ORM module

controller/homeController.php, src/Core/Orm/EntityModel/EntityReflexion.php, src/Core/Orm/EntityModel/Provider/Entity.php, src/Core/Orm/Relations/BaseRelation.php
There was so much duplication function that are doing exactly the same thing except few difference that could be manage with parameters.
closes #120
=> [ENH] refactoring entity reflexion to avois duplication

composer.json, composer.lock
some unused package make the installatio of the project via composer to take somuch time , while they are not used.
Better to use tar ball for `phpunit`, give more flexibility.
closes #123
=> [ENH] remove unused packages

controller/exampleController.php, middleware/Validation/exampleValidation.php, router/route.php, src/Core/Orm/EntityModel/EntityReflexion.php
There was an error where you pascal case on class or class method, which lead to some confusion. so only the first Caracter of the class will be set to lowercase in case the method class is in pascal case.
close #126
=> [FIX] fix error call not defined method.

src/Core/Orm/Traits/QueryExecuter.php
There was a problem while insert an new information, it calls for the include object which is not defined in the insert class. 
It required to check if the object exist.
closes #128.
=> [FIX] try to access undefined object

src/Core/Orm/Traits/QueryExecuter.php
While saved the an new record it was not able to retrieve the last ID because the last id was not provided because we use `executeQuery` method to get the data from the last record. so, we lost the last id. and it return -1. 
closes #129
=> [FIX] Entity save: unable to retrieve last record saved id.

src/Core/Orm/DBUpdate.php
In case we have duplication key it will not be possible to get all information, in case we have a key on the field and on the where condition.
The solution is to get only key value to avoid such problem.
closes #130
=> [UPD] ORM Update: get array without key in case of key duplication

src/Core/Orm/DBSelect.php
While doing a select we call the `formatData` method to parse all data but in case there is not, is has been call which lead to unexpected error.
=> [FIX] ORM Select: try to format data from empty result

src/Core/Orm/EntityModel/Provider/Entity.php
There is a problem with Entity delete method, while trying to delete a row it clean-up the table and in case there is constraint, there will a problem.
The problem is that the condition is not take into consideration. The condition if check after execution.
closes #145
=> [FIX] ORM Entity : error executing delete method before apply condition.

config/autoload.php, config/init.php, src/Core/Orm/DBSelect.php
Each time we try to use 'ASC' or 'DESC' without specifying the order by field we get an error.
closes #151
=> [FIX] error message while using asc or desc without order by.

controller/exampleController.php, index.php, router/route.php, src/Core/Controller.php, src/Core/Orm/DB.php, src/Core/Orm/DBConfig.php, src/Core/Orm/DBSelect.php, src/Core/Orm/EntityModel/EntityReflexionTrait.php, src/Core/Orm/EntityModel/Provider/Entity.php, src/Core/Orm/Provider/DbProvider.php, src/Core/Orm/Relations/BaseRelation.php, src/Core/Orm/Traits/QueryExecuter.php
[ENH] access database credential from .env file as intern configuration.]
[ENH] improve entity access to manage table inclusion.]
[ENH] setup dbconfig to load connection configuration from .env.]
[ENH] make all request to be executed from attribute table name and be extracted after.] 
[ENH] Update app controller to extend the main base controller.]
closes #150 #152
=> [ENH] improve entity access to manage table inclusion.

config/function.php, config/globals.php, src/Core/MetaData.php, src/Core/View.php, views/404.php, views/home.php
In this PR, we made so much solution to resolved problem from typo error as params,
with a clean route path as simple to write with a function instead of trying to thing   how to write each link to feat the need.
[FIX] fixing type 'false' instead of 'fals']
closes #173 
[FIX] resolve try to access parentNode of undefined]
closes #174 
[ENH] get formatted route path via function]
closes #175
=> [ENH] get formatted route path via function

composer.lock, router/route.php, src/Core/View.php
We were not able to display a simple html content form a simple text and frustrating for a simple demo, 
also be able to get data setup from the view.
The idea was in case we want to use the same controller for simple page or for the API, instead of rewriting twice the same process, we will be able to get existing data from existing configuration, unless there is a specific approach for each case.
=> App view module

config/function.php
Defined and default framework method has been refactoring for a better consistency and better control, to avoid method collision.
=> [ENH] refactor function to check file/directory exists

composer.json, composer.lock, config/function.php, controller/indexController.php, middleware/Validation/exampleValidation.php, src/Core/Http/Controller.php, src/Core/Http/MiddleWare.php, src/Core/Http/Providers/BaseControllerMiddleware.php, src/Core/Http/Providers/Contracts/RequestContract.php, src/Core/Http/Providers/Contracts/ResponseContract.php, src/Core/Http/Redirect.php, src/Core/Http/Request.php, src/Core/Http/Response.php, views/404.php, views/home.php
[ENH] change route_path by url route path for easy access]
[ENH] add json extension to be required for http json response]
[ENH] migrate controller from core to http]
[ENH] migrate middleware from core to http]
[ENH] Add media module to be support on controller and middleware]
[UPD] set up method scopes]
[ENH] setup Request to use the RequestContract]
[ENH] setup Response to use the ResponseContract]
=> Refactor Http Controller and Middleware to handle future new feature from base controller and middleware

controller/indexController.php, src/Core/Views/Provider/Contract/ViewsContract.php, src/Core/Views/Provider/ViewBuilderProvider.php, src/Core/Views/View.php
[UPD] remove useless class]
[UPD] update view component and setup view generics]
=> [UPD]Update view extension required

config/function.php, config/init.php, config/tra.php
The translation module s verry poor, a nice default structure and setup by default, that waiting to use to start his own process without knowing how to deal with.
=> [ENH] refactor application translation base module

controller/exampleController.php, middleware/Validation/exampleValidation.php, src/Core/Http/Input.php
We used to used `Input::get()` method to read data from http request `GET` , `POST` and `PUT` without any distinction, that lead for some confusion, in case we want to deal with post, put, there was not a specific way to deal with.
The approach to have each method for a specific case it makes the module more readable and more mature, and void confusion.
closes #205
=> [ENH] refactor http input to trigger each specific action, from GET, POST, PUT and FILES

src/Core/DotEnv.php
it was possible to access user data via global variable, that required to be removed.
closes #180
=> [FIX] Restrict global variable to access users data
